[package]
name = "binst"
version = "0.0.0"
authors = ["Jeremy Chone <jeremy.chone@gmail.com>"]
edition = "2018"
description = "binst's goal is to provide a simple way to publish and install Rust based binaries without the need of cargo-install and the complexity of OS dependent package managers"
homepage = "https://github.com/jeremychone/rust-binst"
repository = "https://github.com/jeremychone/rust-binst"
keywords = [
	"cli",
	"binary",
	"install",
	"publish"
]
categories = ["command-line-interface"]
license = "MIT"

[dependencies]
dirs = "3.0"
clap = "2.33.3"
thiserror = "1.0"
# serde_json = "1.0"
# tar = "0.4"
# walkdir = "2"
# globwalk = "0.8.1"
# libflate = "1"